FROM ruby:3.3.6

# タイムゾーンを設定
ENV TZ=Asia/Tokyo

# 必要なパッケージのインストール
RUN apt-get update -qq && \
    apt-get install -y ca-certificates curl gnupg build-essential libpq-dev vim && \
    mkdir -p /etc/apt/keyrings && \
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg

# Node.jsのセットアップ
RUN NODE_MAJOR=20 && \
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list && \
    apt-get update && apt-get install -y nodejs

# Yarnのインストール
RUN npm install -g yarn

# ChromiumとChromiumドライバーのインストール
RUN apt-get update && apt-get install -y chromium chromium-driver

# 作業ディレクトリの設定
WORKDIR /app

# Gemfileとpackage.jsonをコピー
COPY Gemfile Gemfile.lock ./
COPY package.json yarn.lock ./

# Bundlerの設定とGemのインストール
RUN gem install bundler && \
    bundle config set --local without 'development' && \
    bundle install

# npmパッケージのインストール
RUN yarn install

# アプリケーションコードをコピー
COPY . .

# テスト実行用のコマンド
CMD ["bundle", "exec", "rspec"]
