services:
  - type: web
    name: parts-sync
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: parts_sync_db
          property: connectionString
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: true

databases:
  - name: parts_sync_db
    databaseName: parts_sync_production
    user: parts_sync
    plan: free
