# 毎時5分にEbayの注文を同期
sync_ebay_orders:
  cron: '5 * * * *' # 毎時5分に実行
  class: EbayOrdersSyncJob
  queue: default
  description: 'Fetch eBay orders and save to DB'

# 毎時10分にEbayの取引手数料を同期
sync_ebay_transaction_fees:
  cron: '10 * * * *' # 毎時10分に実行
  class: EbayTransactionFeesSyncJob
  queue: default
  description: 'Fetch eBay transaction fees and save to DB'
